# Generated by Django 4.1.4 on 2023-10-27 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("journalstore", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="journals",
            field=models.ManyToManyField(
                related_name="labels", to="journalstore.journalentry"
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="journal_style",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="journalstore.journalstyle",
            ),
        ),
        migrations.AlterField(
            model_name="journalstyle",
            name="background_color",
            field=models.CharField(default="#FFFFFF", max_length=50),
        ),
        migrations.AlterField(
            model_name="journalstyle",
            name="font",
            field=models.TextField(default="Arial, sans-serif"),
        ),
        migrations.AlterField(
            model_name="journalstyle",
            name="font_color",
            field=models.CharField(default="#000000", max_length=50),
        ),
        migrations.AlterField(
            model_name="journalstyle",
            name="font_size",
            field=models.CharField(default="16px", max_length=50),
        ),
    ]
