# Generated by Django 4.1.4 on 2023-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("journalstore", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="journalentry",
            constraint=models.UniqueConstraint(
                fields=("user", "title"), name="unique_user_title"
            ),
        ),
    ]
