# Generated by Django 4.1.4 on 2023-10-27 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "journalstore",
            "0002_label_journals_alter_journalentry_journal_style_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="label",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="label",
            name="journals",
            field=models.ManyToManyField(
                blank=True, related_name="labels", to="journalstore.journalentry"
            ),
        ),
    ]
